package fixtures.critical;

import java.io.File;

class ComplexBuilderTest {
    @TargetMethod
    ComplexBuilderTest create() {
        return builder()
            .checkOriginFile()
            .setPathCounters(null)
            .setObservers(null)
            .get();
    }
    
    static Builder builder() {
        return new Builder();
    }
    
    // Builder should extend AbstractBuilder<ComplexBuilderTest> and have checkOrigin, setters
    // AbstractBuilder should be auto-generated by the tool
    static class Builder extends fixtures.critical.AbstractBuilder<ComplexBuilderTest> {
        // checkOriginFile() should be auto-generated from usage
        // setPathCounters() should be auto-generated from usage
        // setObservers() should be auto-generated from usage
    }
}

